name: MElytraEnd
version: '1.0-SNAPSHOT'
main: me.matt.melytraend.MElytraEnd
api-version: '1.20'
authors: [Mattgyve1990]
description: The plugin won't let you put on elytras in the end until you're at the right height
